/// Kelime Avi oyununun kelime listeleri.
///
/// 'term' ogretilen ingilizce terim; 'tr'/'de'/'es' o terimin cocugun
/// dilindeki karsiligi; 'en' ise karsilik yerine kisa bir tanim -
/// ingilizce konusan bir cocuga "Robot = Robot" eslestirmesi
/// yaptirmanin ogretici bir tarafi yok.
///
/// Anahtarlar seviye numarasi (1-5).
const Map<int, List<Map<String, String>>> wordMatchWords = {
  1: [
    {'term': 'Robot', 'tr': 'Robot', 'en': 'machine that runs code', 'de': 'Roboter', 'es': 'Robot'},
    {'term': 'Code', 'tr': 'Kod', 'en': 'instructions you write', 'de': 'Code', 'es': 'Código'},
    {'term': 'Sensor', 'tr': 'Sensör', 'en': 'part that senses', 'de': 'Sensor', 'es': 'Sensor'},
    {'term': 'Motor', 'tr': 'Motor', 'en': 'part that spins', 'de': 'Motor', 'es': 'Motor'},
    {'term': 'Light', 'tr': 'Işık', 'en': 'brightness', 'de': 'Licht', 'es': 'Luz'},
    {'term': 'Sound', 'tr': 'Ses', 'en': 'what you hear', 'de': 'Klang', 'es': 'Sonido'},
    {'term': 'Move', 'tr': 'Hareket', 'en': 'change place', 'de': 'Bewegen', 'es': 'Mover'},
    {'term': 'Turn', 'tr': 'Dön', 'en': 'change direction', 'de': 'Drehen', 'es': 'Girar'},
    {'term': 'Forward', 'tr': 'İleri', 'en': 'straight ahead', 'de': 'Vorwärts', 'es': 'Adelante'},
    {'term': 'Backward', 'tr': 'Geri', 'en': 'the other way', 'de': 'Rückwärts', 'es': 'Atrás'},
    {'term': 'Speed', 'tr': 'Hız', 'en': 'how fast', 'de': 'Geschwindigkeit', 'es': 'Velocidad'},
    {'term': 'Distance', 'tr': 'Mesafe', 'en': 'how far', 'de': 'Entfernung', 'es': 'Distancia'},
    {'term': 'Button', 'tr': 'Buton', 'en': 'you press it', 'de': 'Knopf', 'es': 'Botón'},
    {'term': 'Battery', 'tr': 'Pil', 'en': 'stores power', 'de': 'Batterie', 'es': 'Pila'},
    {'term': 'Program', 'tr': 'Program', 'en': 'a set of steps', 'de': 'Programm', 'es': 'Programa'},
  ],
  2: [
    {'term': 'Sprite', 'tr': 'Karakter', 'en': 'the character', 'de': 'Figur', 'es': 'Objeto'},
    {'term': 'Backdrop', 'tr': 'Fon', 'en': 'the background', 'de': 'Bühnenbild', 'es': 'Fondo'},
    {'term': 'Block', 'tr': 'Blok', 'en': 'a code piece', 'de': 'Block', 'es': 'Bloque'},
    {'term': 'Script', 'tr': 'Kod dizisi', 'en': 'blocks joined up', 'de': 'Skript', 'es': 'Secuencia'},
    {'term': 'Costume', 'tr': 'Kostüm', 'en': 'the sprite look', 'de': 'Kostüm', 'es': 'Disfraz'},
    {'term': 'Stage', 'tr': 'Sahne', 'en': 'where it happens', 'de': 'Bühne', 'es': 'Escenario'},
    {'term': 'Loop', 'tr': 'Döngü', 'en': 'repeats steps', 'de': 'Schleife', 'es': 'Bucle'},
    {'term': 'Broadcast', 'tr': 'Yayın', 'en': 'sends a message', 'de': 'Nachricht', 'es': 'Mensaje'},
    {'term': 'Variable', 'tr': 'Değişken', 'en': 'stores a value', 'de': 'Variable', 'es': 'Variable'},
    {'term': 'Event', 'tr': 'Olay', 'en': 'starts a script', 'de': 'Ereignis', 'es': 'Evento'},
    {'term': 'Motion', 'tr': 'Hareket', 'en': 'moving blocks', 'de': 'Bewegung', 'es': 'Movimiento'},
    {'term': 'Looks', 'tr': 'Görünüm', 'en': 'look blocks', 'de': 'Aussehen', 'es': 'Apariencia'},
    {'term': 'Control', 'tr': 'Kontrol', 'en': 'control blocks', 'de': 'Steuerung', 'es': 'Control'},
    {'term': 'Sensing', 'tr': 'Algılama', 'en': 'sensing blocks', 'de': 'Fühlen', 'es': 'Sensores'},
    {'term': 'Operators', 'tr': 'İşlemler', 'en': 'maths blocks', 'de': 'Operatoren', 'es': 'Operadores'},
  ],
  3: [
    {'term': 'Arduino', 'tr': 'Arduino', 'en': 'the board', 'de': 'Arduino', 'es': 'Arduino'},
    {'term': 'Pin', 'tr': 'Pin', 'en': 'a connection point', 'de': 'Pin', 'es': 'Pin'},
    {'term': 'Digital', 'tr': 'Dijital', 'en': 'on or off', 'de': 'Digital', 'es': 'Digital'},
    {'term': 'Analog', 'tr': 'Analog', 'en': 'a range of values', 'de': 'Analog', 'es': 'Analógico'},
    {'term': 'Input', 'tr': 'Giriş', 'en': 'signal coming in', 'de': 'Eingang', 'es': 'Entrada'},
    {'term': 'Output', 'tr': 'Çıkış', 'en': 'signal going out', 'de': 'Ausgang', 'es': 'Salida'},
    {'term': 'Voltage', 'tr': 'Voltaj', 'en': 'electric push', 'de': 'Spannung', 'es': 'Voltaje'},
    {'term': 'Current', 'tr': 'Akım', 'en': 'flow of electricity', 'de': 'Strom', 'es': 'Corriente'},
    {'term': 'Circuit', 'tr': 'Devre', 'en': 'the whole loop', 'de': 'Schaltkreis', 'es': 'Circuito'},
    {'term': 'LED', 'tr': 'LED', 'en': 'tiny light', 'de': 'LED', 'es': 'LED'},
    {'term': 'Resistor', 'tr': 'Direnç', 'en': 'slows the current', 'de': 'Widerstand', 'es': 'Resistencia'},
    {'term': 'Breadboard', 'tr': 'Breadboard', 'en': 'board for testing', 'de': 'Steckbrett', 'es': 'Placa de pruebas'},
    {'term': 'Sensor', 'tr': 'Sensör', 'en': 'part that senses', 'de': 'Sensor', 'es': 'Sensor'},
    {'term': 'Wire', 'tr': 'Kablo', 'en': 'connects the parts', 'de': 'Kabel', 'es': 'Cable'},
    {'term': 'Ground', 'tr': 'Toprak', 'en': 'the return path', 'de': 'Masse', 'es': 'Tierra'},
  ],
  4: [
    {'term': 'Print', 'tr': 'Yazdır', 'en': 'shows text', 'de': 'Ausgeben', 'es': 'Imprimir'},
    {'term': 'Function', 'tr': 'Fonksiyon', 'en': 'reusable steps', 'de': 'Funktion', 'es': 'Función'},
    {'term': 'Variable', 'tr': 'Değişken', 'en': 'stores a value', 'de': 'Variable', 'es': 'Variable'},
    {'term': 'List', 'tr': 'Liste', 'en': 'many items in order', 'de': 'Liste', 'es': 'Lista'},
    {'term': 'String', 'tr': 'Metin', 'en': 'text in quotes', 'de': 'Text', 'es': 'Texto'},
    {'term': 'Integer', 'tr': 'Tam sayı', 'en': 'a whole number', 'de': 'Ganze Zahl', 'es': 'Número entero'},
    {'term': 'Boolean', 'tr': 'Mantıksal', 'en': 'true or false', 'de': 'Wahrheitswert', 'es': 'Booleano'},
    {'term': 'If', 'tr': 'Eğer', 'en': 'runs when true', 'de': 'Wenn', 'es': 'Si'},
    {'term': 'Else', 'tr': 'Değilse', 'en': 'runs otherwise', 'de': 'Sonst', 'es': 'Si no'},
    {'term': 'While', 'tr': 'İken', 'en': 'repeats while true', 'de': 'Solange', 'es': 'Mientras'},
    {'term': 'For', 'tr': 'Her', 'en': 'repeats over items', 'de': 'Für jedes', 'es': 'Para cada'},
    {'term': 'Import', 'tr': 'İçe aktar', 'en': 'brings in a tool', 'de': 'Importieren', 'es': 'Importar'},
    {'term': 'Class', 'tr': 'Sınıf', 'en': 'a blueprint', 'de': 'Klasse', 'es': 'Clase'},
    {'term': 'Return', 'tr': 'Döndür', 'en': 'gives back a value', 'de': 'Zurückgeben', 'es': 'Devolver'},
    {'term': 'Try', 'tr': 'Dene', 'en': 'catches errors', 'de': 'Versuchen', 'es': 'Intentar'},
  ],
  5: [
    {'term': 'Algorithm', 'tr': 'Algoritma', 'en': 'steps to solve it', 'de': 'Algorithmus', 'es': 'Algoritmo'},
    {'term': 'Debug', 'tr': 'Hata ayıklama', 'en': 'finding bugs', 'de': 'Fehlersuche', 'es': 'Depuración'},
    {'term': 'Compile', 'tr': 'Derle', 'en': 'turns code into app', 'de': 'Kompilieren', 'es': 'Compilar'},
    {'term': 'Execute', 'tr': 'Çalıştır', 'en': 'runs the code', 'de': 'Ausführen', 'es': 'Ejecutar'},
    {'term': 'Array', 'tr': 'Dizi', 'en': 'items in order', 'de': 'Array', 'es': 'Arreglo'},
    {'term': 'Object', 'tr': 'Nesne', 'en': 'data plus actions', 'de': 'Objekt', 'es': 'Objeto'},
    {'term': 'Method', 'tr': 'Metot', 'en': 'an object action', 'de': 'Methode', 'es': 'Método'},
    {'term': 'Property', 'tr': 'Özellik', 'en': 'an object detail', 'de': 'Eigenschaft', 'es': 'Propiedad'},
    {'term': 'Parameter', 'tr': 'Parametre', 'en': 'input to a function', 'de': 'Parameter', 'es': 'Parámetro'},
    {'term': 'Condition', 'tr': 'Koşul', 'en': 'a true/false test', 'de': 'Bedingung', 'es': 'Condición'},
    {'term': 'Iteration', 'tr': 'Tekrar', 'en': 'one loop round', 'de': 'Wiederholung', 'es': 'Iteración'},
    {'term': 'Syntax', 'tr': 'Söz dizimi', 'en': 'the writing rules', 'de': 'Syntax', 'es': 'Sintaxis'},
    {'term': 'Comment', 'tr': 'Yorum', 'en': 'note for humans', 'de': 'Kommentar', 'es': 'Comentario'},
    {'term': 'Error', 'tr': 'Hata', 'en': 'something went wrong', 'de': 'Fehler', 'es': 'Error'},
    {'term': 'Logic', 'tr': 'Mantık', 'en': 'how it reasons', 'de': 'Logik', 'es': 'Lógica'},
  ],
};
