# -*- coding: utf-8 -*-
"""Proje adimlarinin gereksinim ve ipuclari, dort dilde.

BLOK ETIKETLERI UYDURULMADI. Scratch bloklarinin adlari
`tool/bloklar/scratch_{tr,en,de,es}.json` (scratch-l10n), mBlock
bloklarininki `tool/bloklar/mblock_*.json` (Makeblock'un canli
i18n dosyasi) dosyalarindan alindi. Cocuk uygulamada okudugu blogu
editorde birebir ayni yaziyla bulmali; "neredeyse ayni" bir etiket,
cocugun aradigini bulamamasi demek.

Turkcede resmi Scratch etiketlerinin bir kismi ders metinlerinde
kullanilanlardan FARKLI ("... haberini sal" / "mesaji yayinla",
"... in ikizini yarat" / "klon olustur"). Burada RESMI olan yaziliyor.
"""

VERI = {
 'lib/courses/data/scratch_lessons_data.dart': {

  's2_1_project': {
   'requirements': {
    'tr': ['Boşluk tuşuna basılınca ışık yansın (parlak kılık)',
           'Tekrar basılınca sönsün (karanlık kılık)'],
    'en': ['When the space key is pressed, the light turns on (bright costume)',
           'Pressing it again turns it off (dark costume)'],
    'de': ['Wenn die Leertaste gedrückt wird, geht das Licht an (helles Kostüm)',
           'Beim nächsten Drücken geht es wieder aus (dunkles Kostüm)'],
    'es': ['Al presionar la tecla espacio se enciende la luz (disfraz brillante)',
           'Al presionarla otra vez se apaga (disfraz oscuro)'],
   },
   'hints': {
    'tr': ['Bir değişken kullan: ışık_açık',
           '"eğer <ışık_açık = 1> ise" ile karanlık kılığa geç',
           'Değilse parlak kılığa geç'],
    'en': ['Use a variable: light_on',
           'Use "if <light_on = 1> then" to switch to the dark costume',
           'Otherwise switch to the bright costume'],
    'de': ['Benutze eine Variable: licht_an',
           'Wechsle mit "falls <licht_an = 1>, dann" zum dunklen Kostüm',
           'Sonst wechsle zum hellen Kostüm'],
    'es': ['Usa una variable: luz_encendida',
           'Con "si <luz_encendida = 1> entonces" cambia al disfraz oscuro',
           'Si no, cambia al disfraz brillante'],
   },
  },

  's3_1_project': {
   'requirements': {
    'tr': ['Kedi 4 yönde hareket etsin',
           'Fare yakalanınca rastgele bir yere kaçsın',
           'Her yakalamada puan artsın',
           'Puanı sahnede göster'],
    'en': ['The cat moves in four directions',
           'When the mouse is caught, it runs to a random spot',
           'Every catch increases the score',
           'Show the score on the stage'],
    'de': ['Die Katze bewegt sich in vier Richtungen',
           'Wird die Maus gefangen, flieht sie an einen zufälligen Ort',
           'Jeder Fang erhöht die Punktzahl',
           'Zeige die Punktzahl auf der Bühne'],
    'es': ['El gato se mueve en cuatro direcciones',
           'Cuando atrapan al ratón, huye a un lugar al azar',
           'Cada captura aumenta la puntuación',
           'Muestra la puntuación en el escenario'],
   },
   'hints': {
    'tr': ['Puan için bir değişken oluştur',
           'Fare kuklası için ayrı bir kod yaz',
           '"rastgele bir sayı seç" bloğuyla kaçacağı yeri belirle'],
    'en': ['Create a variable for the score',
           'Write separate code for the mouse sprite',
           'Use "pick random" to choose where it runs to'],
    'de': ['Lege eine Variable für die Punktzahl an',
           'Schreibe eigenen Code für die Maus-Figur',
           'Wähle mit "Zufallszahl von ... bis ..." das Fluchtziel'],
    'es': ['Crea una variable para la puntuación',
           'Escribe código aparte para el objeto ratón',
           'Elige el destino con "número aleatorio entre ... y ..."'],
   },
  },

  's4_2_project': {
   'requirements': {
    'tr': ['Puan değişkeni oluştur',
           'Her yıldız +10 puan versin',
           'Puanı sahnede göster',
           '50 puana ulaşınca "Kazandın!" de'],
    'en': ['Create a score variable',
           'Each star gives +10 points',
           'Show the score on the stage',
           'When the score reaches 50, say "You won!"'],
    'de': ['Lege eine Variable für die Punktzahl an',
           'Jeder Stern gibt +10 Punkte',
           'Zeige die Punktzahl auf der Bühne',
           'Sage bei 50 Punkten "Du hast gewonnen!"'],
    'es': ['Crea una variable de puntuación',
           'Cada estrella da +10 puntos',
           'Muestra la puntuación en el escenario',
           'Al llegar a 50 puntos di "¡Ganaste!"'],
   },
   'hints': {
    'tr': ['Bir yıldız kuklası oluştur',
           'Yıldıza değince "puan i 10 kadar değiştir" bloğunu kullan',
           'Puanı kontrol et: eğer <puan > 49> ise'],
    'en': ['Create a star sprite',
           'When it touches the star, use "change score by 10"',
           'Check the score: if <score > 49> then'],
    'de': ['Lege eine Stern-Figur an',
           'Bei Berührung: "ändere Punkte um 10"',
           'Prüfe die Punktzahl: falls <Punkte > 49>, dann'],
    'es': ['Crea un objeto estrella',
           'Al tocarla usa "sumar a puntuación 10"',
           'Comprueba la puntuación: si <puntuación > 49> entonces'],
   },
  },

  's5_1_project': {
   'requirements': {
    'tr': ['Her 1 saniyede bir yıldızın ikizini yarat',
           'İkizler üstten başlasın',
           'Aşağı düşüp alta gelince silinsin',
           'Kediye değince puan +1'],
    'en': ['Create a clone of the star every second',
           'Clones start at the top',
           'They fall down and are deleted at the bottom',
           'Touching the cat gives +1 point'],
    'de': ['Erzeuge jede Sekunde einen Klon des Sterns',
           'Die Klone starten oben',
           'Sie fallen nach unten und werden unten gelöscht',
           'Berührt ein Klon die Katze, gibt es +1 Punkt'],
    'es': ['Crea un clon de la estrella cada segundo',
           'Los clones empiezan arriba',
           'Caen y se eliminan al llegar abajo',
           'Al tocar al gato dan +1 punto'],
   },
   'hints': {
    'tr': ['"sürekli tekrarla" içinde "1 saniye bekle" ile yarat',
           '"y konumunu -5 değiştir" ile aşağı indir',
           'eğer <y konumu < -170> ise "bu ikizi sil"'],
    'en': ['Use "wait 1 seconds" inside "forever" to keep creating them',
           'Use "change y by -5" to move them down',
           'if <y position < -170> then "delete this clone"'],
    'de': ['Erzeuge sie mit "warte 1 Sekunden" in "wiederhole fortlaufend"',
           'Mit "ändere y um -5" fallen sie nach unten',
           'falls <y-Position < -170>, dann "lösche diesen Klon"'],
    'es': ['Créalos con "esperar 1 segundos" dentro de "por siempre"',
           'Con "sumar a y -5" bajan',
           'si <posición en y < -170> entonces "eliminar este clon"'],
   },
  },

  's6_1_project': {
   'requirements': {
    'tr': ['Kedi "dans_başladı" haberini salsın',
           'Fare haberi alınca dönmeye başlasın',
           'Top haberi alınca zıplasın',
           'Her kukla farklı bir dans yapsın'],
    'en': ['The cat broadcasts "dance_started"',
           'When the mouse receives it, it starts spinning',
           'When the ball receives it, it jumps',
           'Every sprite dances differently'],
    'de': ['Die Katze sendet "tanz_gestartet" an alle',
           'Wenn die Maus es empfängt, dreht sie sich',
           'Wenn der Ball es empfängt, hüpft er',
           'Jede Figur tanzt anders'],
    'es': ['El gato envía "baile_empezo"',
           'Al recibirlo, el ratón empieza a girar',
           'Al recibirlo, la pelota salta',
           'Cada objeto baila de forma distinta'],
   },
   'hints': {
    'tr': ['Sahneye 3 kukla ekle',
           'Kedide: yeşil bayrağa tıklandığında "dans_başladı haberini sal"',
           'Diğer kuklalarda "dans_başladı haberini aldığımda" ile başla'],
    'en': ['Add three sprites to the stage',
           'On the cat: when the green flag is clicked, "broadcast dance_started"',
           'On the others, start with "when I receive dance_started"'],
    'de': ['Füge drei Figuren zur Bühne hinzu',
           'Bei der Katze: Wenn die grüne Flagge angeklickt wird, "sende tanz_gestartet an alle"',
           'Bei den anderen: beginne mit "Wenn ich tanz_gestartet empfange"'],
    'es': ['Añade tres objetos al escenario',
           'En el gato: al hacer clic en la bandera verde, "enviar baile_empezo"',
           'En los demás empieza con "al recibir baile_empezo"'],
   },
  },

  's7_1_project': {
   'requirements': {
    'tr': ['5 tuş: A, S, D, F, G',
           'Her tuş farklı bir nota çalsın (60, 62, 64, 65, 67)',
           'Tuşa basılınca nota çalsın'],
    'en': ['Five keys: A, S, D, F, G',
           'Each key plays a different note (60, 62, 64, 65, 67)',
           'The note plays when the key is pressed'],
    'de': ['Fünf Tasten: A, S, D, F, G',
           'Jede Taste spielt eine andere Note (60, 62, 64, 65, 67)',
           'Die Note erklingt, wenn die Taste gedrückt wird'],
    'es': ['Cinco teclas: A, S, D, F, G',
           'Cada tecla toca una nota distinta (60, 62, 64, 65, 67)',
           'La nota suena al presionar la tecla'],
   },
   'hints': {
    'tr': ['Her tuş için "a tuşuna basılınca" bloğunu kullan',
           'Nota bloğu Müzik eklentisinde',
           'Her tuşun notası farklı olsun'],
    'en': ['Use "when a key pressed" for each key',
           'The note block is in the Music extension',
           'Give every key its own note'],
    'de': ['Benutze für jede Taste "Wenn Taste a gedrückt wird"',
           'Der Notenblock ist in der Erweiterung Musik',
           'Gib jeder Taste eine eigene Note'],
    'es': ['Usa "al presionar tecla a" para cada tecla',
           'El bloque de nota está en la extensión Música',
           'Da a cada tecla su propia nota'],
   },
  },

 },

 'lib/courses/data/csharp_lessons_data.dart': {

  'cs1_2_project': {
   'requirements': {
    'tr': ['class ile bir sınıf oluştur', 'Main metodunu yaz (büyük M!)',
           'En az 3 Console.WriteLine() satırı kullan (isim, yaş, hobi)'],
    'en': ['Create a class with class', 'Write the Main method (capital M!)',
           'Use at least three Console.WriteLine() lines (name, age, hobby)'],
    'de': ['Lege mit class eine Klasse an', 'Schreibe die Main-Methode (grosses M!)',
           'Benutze mindestens drei Console.WriteLine()-Zeilen (Name, Alter, Hobby)'],
    'es': ['Crea una clase con class', 'Escribe el método Main (¡con M mayúscula!)',
           'Usa al menos tres líneas Console.WriteLine() (nombre, edad, afición)'],
   },
   'hints': {
    'tr': ['Console.WriteLine("Adım: Ahmet");', 'Console.WriteLine("Yaşım: 12");',
           'Her satırın sonunda ; olmalı'],
    'en': ['Console.WriteLine("My name: Ahmet");', 'Console.WriteLine("My age: 12");',
           'Every line must end with ;'],
    'de': ['Console.WriteLine("Mein Name: Ahmet");', 'Console.WriteLine("Mein Alter: 12");',
           'Jede Zeile muss mit ; enden'],
    'es': ['Console.WriteLine("Me llamo: Ahmet");', 'Console.WriteLine("Tengo: 12");',
           'Cada línea debe terminar con ;'],
   },
  },

  'cs2_2_project': {
   'requirements': {
    'tr': ['for döngüsü kullan', '1\'den 10\'a kadar bütün sayıları yazdır',
           'Console.WriteLine() kullan'],
    'en': ['Use a for loop', 'Print every number from 1 to 10',
           'Use Console.WriteLine()'],
    'de': ['Benutze eine for-Schleife', 'Gib alle Zahlen von 1 bis 10 aus',
           'Benutze Console.WriteLine()'],
    'es': ['Usa un bucle for', 'Escribe todos los números del 1 al 10',
           'Usa Console.WriteLine()'],
   },
   'hints': {
    'tr': ['for (int i = 1; i <= 10; i++) {', 'Console.WriteLine(i);'],
    'en': ['for (int i = 1; i <= 10; i++) {', 'Console.WriteLine(i);'],
    'de': ['for (int i = 1; i <= 10; i++) {', 'Console.WriteLine(i);'],
    'es': ['for (int i = 1; i <= 10; i++) {', 'Console.WriteLine(i);'],
   },
  },

  'cs2_3_project': {
   'requirements': {
    'tr': ['int[] notlar dizisi oluştur (en az 4 not)',
           'foreach ya da for döngüsüyle bütün notları topla',
           'Toplamı eleman sayısına bölerek ortalamayı bul', 'Ortalamayı yazdır'],
    'en': ['Create an int[] notlar array (at least four grades)',
           'Add up every grade with foreach or for',
           'Divide the total by the number of items to get the average',
           'Print the average'],
    'de': ['Lege ein int[] notlar Array an (mindestens vier Noten)',
           'Addiere alle Noten mit foreach oder for',
           'Teile die Summe durch die Anzahl, um den Durchschnitt zu erhalten',
           'Gib den Durchschnitt aus'],
    'es': ['Crea un arreglo int[] notlar (al menos cuatro notas)',
           'Suma todas las notas con foreach o for',
           'Divide el total entre la cantidad para obtener el promedio',
           'Escribe el promedio'],
   },
   'hints': {
    'tr': ['int toplam = 0; foreach (int n in notlar) { toplam += n; }',
           'double ortalama = (double) toplam / notlar.Length;'],
    'en': ['int toplam = 0; foreach (int n in notlar) { toplam += n; }',
           'double ortalama = (double) toplam / notlar.Length;'],
    'de': ['int toplam = 0; foreach (int n in notlar) { toplam += n; }',
           'double ortalama = (double) toplam / notlar.Length;'],
    'es': ['int toplam = 0; foreach (int n in notlar) { toplam += n; }',
           'double ortalama = (double) toplam / notlar.Length;'],
   },
  },

  'cs3_2_project': {
   'requirements': {
    'tr': ['Oyuncu sınıfı oluştur (isim, can)',
           'HasarAl(int miktar) adında bir metot yaz',
           'Metot, can değerini miktar kadar azaltsın',
           'Main içinde bir Oyuncu nesnesi oluştur ve metodu çağır'],
    'en': ['Create an Oyuncu (player) class with isim and can fields',
           'Write a method called HasarAl(int miktar)',
           'The method lowers can by miktar',
           'Create an Oyuncu object in Main and call the method'],
    'de': ['Lege eine Klasse Oyuncu (Spieler) mit isim und can an',
           'Schreibe eine Methode HasarAl(int miktar)',
           'Die Methode verringert can um miktar',
           'Erzeuge in Main ein Oyuncu-Objekt und rufe die Methode auf'],
    'es': ['Crea una clase Oyuncu (jugador) con isim y can',
           'Escribe un método llamado HasarAl(int miktar)',
           'El método reduce can en miktar',
           'Crea un objeto Oyuncu en Main y llama al método'],
   },
   'hints': {
    'tr': ['public void HasarAl(int miktar) { can -= miktar; }',
           'Oyuncu o = new Oyuncu(); o.HasarAl(20);'],
    'en': ['public void HasarAl(int miktar) { can -= miktar; }',
           'Oyuncu o = new Oyuncu(); o.HasarAl(20);'],
    'de': ['public void HasarAl(int miktar) { can -= miktar; }',
           'Oyuncu o = new Oyuncu(); o.HasarAl(20);'],
    'es': ['public void HasarAl(int miktar) { can -= miktar; }',
           'Oyuncu o = new Oyuncu(); o.HasarAl(20);'],
   },
  },

  'cs4_1_project': {
   'requirements': {
    'tr': ['int puan değişkeni tanımla',
           'if-else if-else zinciriyle harf notunu belirle (A/B/C/F)',
           'Hem puanı hem harf notunu Console.WriteLine ile yazdır'],
    'en': ['Declare an int puan variable',
           'Work out the letter grade with an if-else if-else chain (A/B/C/F)',
           'Print both the score and the letter grade with Console.WriteLine'],
    'de': ['Deklariere eine int-Variable puan',
           'Ermittle die Buchstabennote mit einer if-else if-else-Kette (A/B/C/F)',
           'Gib Punktzahl und Buchstabennote mit Console.WriteLine aus'],
    'es': ['Declara una variable int puan',
           'Determina la nota con una cadena if-else if-else (A/B/C/F)',
           'Escribe la puntuación y la nota con Console.WriteLine'],
   },
   'hints': {
    'tr': ['if (puan >= 90) { harfNotu = "A"; }',
           'Sırayla en yüksekten en düşüğe kontrol et',
           'En son else ile "F" durumunu yakala'],
    'en': ['if (puan >= 90) { harfNotu = "A"; }',
           'Check in order, from the highest down to the lowest',
           'Catch the "F" case with the final else'],
    'de': ['if (puan >= 90) { harfNotu = "A"; }',
           'Prüfe der Reihe nach, von der höchsten zur niedrigsten Grenze',
           'Fange den Fall "F" mit dem letzten else ab'],
    'es': ['if (puan >= 90) { harfNotu = "A"; }',
           'Comprueba en orden, de mayor a menor',
           'Captura el caso "F" con el último else'],
   },
  },

  'cs4_2_project': {
   'requirements': {
    'tr': ['Esya sınıfı tanımla (isim, deger)',
           'List<Esya> ile bir envanter listesi oluştur',
           'En az 3 eşya ekle (Add ile)',
           'foreach ile toplam değeri hesapla ve yazdır'],
    'en': ['Define an Esya (item) class with isim and deger',
           'Create an inventory list with List<Esya>',
           'Add at least three items with Add',
           'Work out the total value with foreach and print it'],
    'de': ['Definiere eine Klasse Esya (Gegenstand) mit isim und deger',
           'Lege mit List<Esya> eine Inventarliste an',
           'Füge mit Add mindestens drei Gegenstände hinzu',
           'Berechne den Gesamtwert mit foreach und gib ihn aus'],
    'es': ['Define una clase Esya (objeto) con isim y deger',
           'Crea una lista de inventario con List<Esya>',
           'Añade al menos tres objetos con Add',
           'Calcula el valor total con foreach y escríbelo'],
   },
   'hints': {
    'tr': ['class Esya { public string isim; public int deger; }',
           'List<Esya> envanter = new List<Esya>();',
           'foreach (Esya e in envanter) { toplamDeger += e.deger; }'],
    'en': ['class Esya { public string isim; public int deger; }',
           'List<Esya> envanter = new List<Esya>();',
           'foreach (Esya e in envanter) { toplamDeger += e.deger; }'],
    'de': ['class Esya { public string isim; public int deger; }',
           'List<Esya> envanter = new List<Esya>();',
           'foreach (Esya e in envanter) { toplamDeger += e.deger; }'],
    'es': ['class Esya { public string isim; public int deger; }',
           'List<Esya> envanter = new List<Esya>();',
           'foreach (Esya e in envanter) { toplamDeger += e.deger; }'],
   },
  },

  'cs4_3_project': {
   'requirements': {
    'tr': ['Karakter sınıfı oluştur (isim, can, HasarAl metodu)',
           'HasarAl metodunda can değerinin 0\'ın altına inmesini engelle',
           'Oyuncu : Karakter ve Dusman : Karakter ile kalıtım kullan',
           'Main içinde bir Oyuncu ve bir Dusman nesnesi oluştur',
           'HasarAl metodunu çağırarak test et ve sonuçları yazdır'],
    'en': ['Create a Karakter class (isim, can, HasarAl method)',
           'In HasarAl, stop can from going below 0',
           'Use inheritance: Oyuncu : Karakter and Dusman : Karakter',
           'Create an Oyuncu and a Dusman object in Main',
           'Test by calling HasarAl and print the results'],
    'de': ['Lege eine Klasse Karakter an (isim, can, Methode HasarAl)',
           'Verhindere in HasarAl, dass can unter 0 fällt',
           'Nutze Vererbung: Oyuncu : Karakter und Dusman : Karakter',
           'Erzeuge in Main ein Oyuncu- und ein Dusman-Objekt',
           'Teste mit HasarAl und gib die Ergebnisse aus'],
    'es': ['Crea una clase Karakter (isim, can, método HasarAl)',
           'En HasarAl impide que can baje de 0',
           'Usa herencia: Oyuncu : Karakter y Dusman : Karakter',
           'Crea un objeto Oyuncu y uno Dusman en Main',
           'Pruébalo llamando a HasarAl y escribe los resultados'],
   },
   'hints': {
    'tr': ['class Karakter { public string isim; public int can = 100; public void HasarAl(int m) {...} }',
           'class Oyuncu : Karakter { public int puan; }',
           'if (can < 0) { can = 0; }'],
    'en': ['class Karakter { public string isim; public int can = 100; public void HasarAl(int m) {...} }',
           'class Oyuncu : Karakter { public int puan; }',
           'if (can < 0) { can = 0; }'],
    'de': ['class Karakter { public string isim; public int can = 100; public void HasarAl(int m) {...} }',
           'class Oyuncu : Karakter { public int puan; }',
           'if (can < 0) { can = 0; }'],
    'es': ['class Karakter { public string isim; public int can = 100; public void HasarAl(int m) {...} }',
           'class Oyuncu : Karakter { public int puan; }',
           'if (can < 0) { can = 0; }'],
   },
  },

 },

 'lib/courses/data/java_lessons_data.dart': {

  'j1_2_project': {
   'requirements': {
    'tr': ['public class ile bir sınıf oluştur', 'main metodunu yaz',
           'En az 3 System.out.println() satırı kullan (isim, yaş, hobi)'],
    'en': ['Create a class with public class', 'Write the main method',
           'Use at least three System.out.println() lines (name, age, hobby)'],
    'de': ['Lege mit public class eine Klasse an', 'Schreibe die main-Methode',
           'Benutze mindestens drei System.out.println()-Zeilen (Name, Alter, Hobby)'],
    'es': ['Crea una clase con public class', 'Escribe el método main',
           'Usa al menos tres líneas System.out.println() (nombre, edad, afición)'],
   },
   'hints': {
    'tr': ['System.out.println("Adım: Ahmet");', 'System.out.println("Yaşım: 12");',
           'Her satırın sonunda ; olmalı'],
    'en': ['System.out.println("My name: Ahmet");', 'System.out.println("My age: 12");',
           'Every line must end with ;'],
    'de': ['System.out.println("Mein Name: Ahmet");', 'System.out.println("Mein Alter: 12");',
           'Jede Zeile muss mit ; enden'],
    'es': ['System.out.println("Me llamo: Ahmet");', 'System.out.println("Tengo: 12");',
           'Cada línea debe terminar con ;'],
   },
  },

  'j2_2_project': {
   'requirements': {
    'tr': ['for döngüsü kullan', "1'den 10'a kadar bütün sayıları yazdır",
           'System.out.println() kullan'],
    'en': ['Use a for loop', 'Print every number from 1 to 10',
           'Use System.out.println()'],
    'de': ['Benutze eine for-Schleife', 'Gib alle Zahlen von 1 bis 10 aus',
           'Benutze System.out.println()'],
    'es': ['Usa un bucle for', 'Escribe todos los números del 1 al 10',
           'Usa System.out.println()'],
   },
   'hints': {
    'tr': ['for (int i = 1; i <= 10; i++) {', 'System.out.println(i);'],
    'en': ['for (int i = 1; i <= 10; i++) {', 'System.out.println(i);'],
    'de': ['for (int i = 1; i <= 10; i++) {', 'System.out.println(i);'],
    'es': ['for (int i = 1; i <= 10; i++) {', 'System.out.println(i);'],
   },
  },

  'j2_3_project': {
   'requirements': {
    'tr': ['int[] notlar dizisi oluştur (en az 4 not)',
           'for döngüsüyle bütün notları topla',
           'Toplamı eleman sayısına bölerek ortalamayı bul', 'Ortalamayı yazdır'],
    'en': ['Create an int[] notlar array (at least four grades)',
           'Add up every grade with a for loop',
           'Divide the total by the number of items to get the average',
           'Print the average'],
    'de': ['Lege ein int[] notlar Array an (mindestens vier Noten)',
           'Addiere alle Noten mit einer for-Schleife',
           'Teile die Summe durch die Anzahl, um den Durchschnitt zu erhalten',
           'Gib den Durchschnitt aus'],
    'es': ['Crea un arreglo int[] notlar (al menos cuatro notas)',
           'Suma todas las notas con un bucle for',
           'Divide el total entre la cantidad para obtener el promedio',
           'Escribe el promedio'],
   },
   'hints': {
    'tr': ['int toplam = 0; for (...) { toplam += notlar[i]; }',
           'double ortalama = toplam / (double) notlar.length;'],
    'en': ['int toplam = 0; for (...) { toplam += notlar[i]; }',
           'double ortalama = toplam / (double) notlar.length;'],
    'de': ['int toplam = 0; for (...) { toplam += notlar[i]; }',
           'double ortalama = toplam / (double) notlar.length;'],
    'es': ['int toplam = 0; for (...) { toplam += notlar[i]; }',
           'double ortalama = toplam / (double) notlar.length;'],
   },
  },

  'j3_2_project': {
   'requirements': {
    'tr': ['Ogrenci sınıfı oluştur (isim, notlar dizisi)',
           'ortalamaHesapla() adında bir metot yaz',
           'Metot, notların ortalamasını return etsin',
           'main içinde bir Ogrenci nesnesi oluştur ve metodu çağır'],
    'en': ['Create an Ogrenci (student) class with isim and a notlar array',
           'Write a method called ortalamaHesapla()',
           'The method returns the average of the grades',
           'Create an Ogrenci object in main and call the method'],
    'de': ['Lege eine Klasse Ogrenci (Schueler) mit isim und einem notlar-Array an',
           'Schreibe eine Methode ortalamaHesapla()',
           'Die Methode gibt den Durchschnitt der Noten zurück',
           'Erzeuge in main ein Ogrenci-Objekt und rufe die Methode auf'],
    'es': ['Crea una clase Ogrenci (alumno) con isim y un arreglo notlar',
           'Escribe un método llamado ortalamaHesapla()',
           'El método devuelve el promedio de las notas',
           'Crea un objeto Ogrenci en main y llama al método'],
   },
   'hints': {
    'tr': ['double ortalamaHesapla() { ... return (double) toplam / notlar.length; }',
           'Ogrenci o = new Ogrenci(); o.ortalamaHesapla();'],
    'en': ['double ortalamaHesapla() { ... return (double) toplam / notlar.length; }',
           'Ogrenci o = new Ogrenci(); o.ortalamaHesapla();'],
    'de': ['double ortalamaHesapla() { ... return (double) toplam / notlar.length; }',
           'Ogrenci o = new Ogrenci(); o.ortalamaHesapla();'],
    'es': ['double ortalamaHesapla() { ... return (double) toplam / notlar.length; }',
           'Ogrenci o = new Ogrenci(); o.ortalamaHesapla();'],
   },
  },

  'j4_1_project': {
   'requirements': {
    'tr': ['int puan değişkeni tanımla',
           'if-else if-else zinciriyle harf notunu belirle (A/B/C/F)',
           'Hem puanı hem harf notunu System.out.println ile yazdır'],
    'en': ['Declare an int puan variable',
           'Work out the letter grade with an if-else if-else chain (A/B/C/F)',
           'Print both the score and the letter grade with System.out.println'],
    'de': ['Deklariere eine int-Variable puan',
           'Ermittle die Buchstabennote mit einer if-else if-else-Kette (A/B/C/F)',
           'Gib Punktzahl und Buchstabennote mit System.out.println aus'],
    'es': ['Declara una variable int puan',
           'Determina la nota con una cadena if-else if-else (A/B/C/F)',
           'Escribe la puntuación y la nota con System.out.println'],
   },
   'hints': {
    'tr': ['if (puan >= 90) { harfNotu = "A"; }',
           'Sırayla en yüksekten en düşüğe kontrol et',
           'En son else ile "F" durumunu yakala'],
    'en': ['if (puan >= 90) { harfNotu = "A"; }',
           'Check in order, from the highest down to the lowest',
           'Catch the "F" case with the final else'],
    'de': ['if (puan >= 90) { harfNotu = "A"; }',
           'Prüfe der Reihe nach, von der höchsten zur niedrigsten Grenze',
           'Fange den Fall "F" mit dem letzten else ab'],
    'es': ['if (puan >= 90) { harfNotu = "A"; }',
           'Comprueba en orden, de mayor a menor',
           'Captura el caso "F" con el último else'],
   },
  },

  'j4_2_project': {
   'requirements': {
    'tr': ['Ogrenci sınıfı tanımla (isim, notlar[])',
           'ortalamaHesapla() metodunu ekle',
           'En az 2 Ogrenci nesnesi oluştur',
           'Her ikisinin de ismini ve ortalamasını yazdır'],
    'en': ['Define an Ogrenci class (isim, notlar[])',
           'Add the ortalamaHesapla() method',
           'Create at least two Ogrenci objects',
           'Print the name and the average of both'],
    'de': ['Definiere eine Klasse Ogrenci (isim, notlar[])',
           'Füge die Methode ortalamaHesapla() hinzu',
           'Erzeuge mindestens zwei Ogrenci-Objekte',
           'Gib von beiden Namen und Durchschnitt aus'],
    'es': ['Define una clase Ogrenci (isim, notlar[])',
           'Añade el método ortalamaHesapla()',
           'Crea al menos dos objetos Ogrenci',
           'Escribe el nombre y el promedio de ambos'],
   },
   'hints': {
    'tr': ['class Ogrenci { String isim; int[] notlar; double ortalamaHesapla() {...} }',
           'Ogrenci o1 = new Ogrenci(); o1.isim = "Ali";',
           'Ortalamayı hesaplarken (double) dönüşümünü unutma'],
    'en': ['class Ogrenci { String isim; int[] notlar; double ortalamaHesapla() {...} }',
           'Ogrenci o1 = new Ogrenci(); o1.isim = "Ali";',
           'Do not forget the (double) cast when working out the average'],
    'de': ['class Ogrenci { String isim; int[] notlar; double ortalamaHesapla() {...} }',
           'Ogrenci o1 = new Ogrenci(); o1.isim = "Ali";',
           'Vergiss beim Durchschnitt die (double)-Umwandlung nicht'],
    'es': ['class Ogrenci { String isim; int[] notlar; double ortalamaHesapla() {...} }',
           'Ogrenci o1 = new Ogrenci(); o1.isim = "Ali";',
           'No olvides la conversión (double) al calcular el promedio'],
   },
  },

  'j4_3_project': {
   'requirements': {
    'tr': ['HesapMakinesi sınıfı oluştur',
           'topla, cikar, carp, bol metotlarını yaz (hepsi double döndürsün)',
           'bol metodunda sıfıra bölme kontrolü yap (if ile)',
           'main içinde HesapMakinesi nesnesi oluştur ve bütün işlemleri dene',
           'Sonuçları System.out.println ile yazdır'],
    'en': ['Create a HesapMakinesi (calculator) class',
           'Write the methods topla, cikar, carp and bol (all return double)',
           'Guard against division by zero inside bol (with if)',
           'Create a HesapMakinesi object in main and try every operation',
           'Print the results with System.out.println'],
    'de': ['Lege eine Klasse HesapMakinesi (Rechner) an',
           'Schreibe die Methoden topla, cikar, carp und bol (alle geben double zurück)',
           'Fange in bol die Division durch null ab (mit if)',
           'Erzeuge in main ein HesapMakinesi-Objekt und teste alle Rechnungen',
           'Gib die Ergebnisse mit System.out.println aus'],
    'es': ['Crea una clase HesapMakinesi (calculadora)',
           'Escribe los métodos topla, cikar, carp y bol (todos devuelven double)',
           'Controla la división por cero dentro de bol (con if)',
           'Crea un objeto HesapMakinesi en main y prueba todas las operaciones',
           'Escribe los resultados con System.out.println'],
   },
   'hints': {
    'tr': ['class HesapMakinesi { double topla(double a, double b) { return a+b; } }',
           'bol metodunda: if (b == 0) { ... return 0; }',
           'HesapMakinesi hm = new HesapMakinesi(); hm.topla(2,3);'],
    'en': ['class HesapMakinesi { double topla(double a, double b) { return a+b; } }',
           'Inside bol: if (b == 0) { ... return 0; }',
           'HesapMakinesi hm = new HesapMakinesi(); hm.topla(2,3);'],
    'de': ['class HesapMakinesi { double topla(double a, double b) { return a+b; } }',
           'In bol: if (b == 0) { ... return 0; }',
           'HesapMakinesi hm = new HesapMakinesi(); hm.topla(2,3);'],
    'es': ['class HesapMakinesi { double topla(double a, double b) { return a+b; } }',
           'Dentro de bol: if (b == 0) { ... return 0; }',
           'HesapMakinesi hm = new HesapMakinesi(); hm.topla(2,3);'],
   },
  },

 },

 'lib/courses/data/css_lessons_data.dart': {

  'c2_3_project': {
   'requirements': {
    'tr': ['width ve height ile boyut ver', 'padding ile iç boşluk ekle',
           'border-radius ile köşeleri yuvarla', 'box-shadow ile gölge ekle'],
    'en': ['Give it a size with width and height', 'Add inner space with padding',
           'Round the corners with border-radius', 'Add a shadow with box-shadow'],
    'de': ['Gib ihr mit width und height eine Größe', 'Füge mit padding Innenabstand hinzu',
           'Runde die Ecken mit border-radius', 'Füge mit box-shadow einen Schatten hinzu'],
    'es': ['Dale tamaño con width y height', 'Añade espacio interior con padding',
           'Redondea las esquinas con border-radius', 'Añade una sombra con box-shadow'],
   },
   'hints': {
    'tr': ['.kart { width: 250px; padding: 20px; }',
           'border-radius: 16px; deneyebilirsin',
           'box-shadow: 0px 4px 12px rgba(0,0,0,0.15);'],
    'en': ['.kart { width: 250px; padding: 20px; }',
           'You can try border-radius: 16px;',
           'box-shadow: 0px 4px 12px rgba(0,0,0,0.15);'],
    'de': ['.kart { width: 250px; padding: 20px; }',
           'Probier border-radius: 16px;',
           'box-shadow: 0px 4px 12px rgba(0,0,0,0.15);'],
    'es': ['.kart { width: 250px; padding: 20px; }',
           'Puedes probar border-radius: 16px;',
           'box-shadow: 0px 4px 12px rgba(0,0,0,0.15);'],
   },
  },

  'c3_3_project': {
   'requirements': {
    'tr': ['display: flex kullan',
           'flex-wrap: wrap ile satır atlamayı sağla',
           'gap ile kartların arasına boşluk koy', 'justify-content ile hizala'],
    'en': ['Use display: flex',
           'Let the items wrap with flex-wrap: wrap',
           'Put space between the cards with gap', 'Align them with justify-content'],
    'de': ['Benutze display: flex',
           'Lass den Umbruch mit flex-wrap: wrap zu',
           'Setze mit gap Abstand zwischen die Karten', 'Richte sie mit justify-content aus'],
    'es': ['Usa display: flex',
           'Permite el salto de línea con flex-wrap: wrap',
           'Pon espacio entre las tarjetas con gap', 'Alinéalas con justify-content'],
   },
   'hints': {
    'tr': ['.galeri { display: flex; flex-wrap: wrap; gap: 16px; }',
           'justify-content: center; ile ortalayabilirsin'],
    'en': ['.galeri { display: flex; flex-wrap: wrap; gap: 16px; }',
           'You can centre them with justify-content: center;'],
    'de': ['.galeri { display: flex; flex-wrap: wrap; gap: 16px; }',
           'Mit justify-content: center; zentrierst du sie'],
    'es': ['.galeri { display: flex; flex-wrap: wrap; gap: 16px; }',
           'Puedes centrarlas con justify-content: center;'],
   },
  },

  'c4_3_project': {
   'requirements': {
    'tr': ['Kutu modeli: width, padding, border-radius kullan',
           'box-shadow ile gölge ekle',
           'Flexbox ile içeriği ortala (display: flex, align-items)',
           'Hover efekti ekle (:hover, transform: scale)',
           'transition ile yumuşak geçiş sağla'],
    'en': ['Box model: use width, padding and border-radius',
           'Add a shadow with box-shadow',
           'Centre the content with flexbox (display: flex, align-items)',
           'Add a hover effect (:hover, transform: scale)',
           'Make the change smooth with transition'],
    'de': ['Boxmodell: benutze width, padding und border-radius',
           'Füge mit box-shadow einen Schatten hinzu',
           'Zentriere den Inhalt mit Flexbox (display: flex, align-items)',
           'Füge einen Hover-Effekt hinzu (:hover, transform: scale)',
           'Mach den Übergang mit transition weich'],
    'es': ['Modelo de caja: usa width, padding y border-radius',
           'Añade una sombra con box-shadow',
           'Centra el contenido con flexbox (display: flex, align-items)',
           'Añade un efecto hover (:hover, transform: scale)',
           'Suaviza el cambio con transition'],
   },
   'hints': {
    'tr': ['.profil-karti { width: 280px; padding: 24px; border-radius: 16px; }',
           'display: flex; flex-direction: column; align-items: center;',
           '.profil-karti:hover { transform: scale(1.03); }',
           'transition: transform 0.3s; yazmayı unutma!'],
    'en': ['.profil-karti { width: 280px; padding: 24px; border-radius: 16px; }',
           'display: flex; flex-direction: column; align-items: center;',
           '.profil-karti:hover { transform: scale(1.03); }',
           'Do not forget transition: transform 0.3s;'],
    'de': ['.profil-karti { width: 280px; padding: 24px; border-radius: 16px; }',
           'display: flex; flex-direction: column; align-items: center;',
           '.profil-karti:hover { transform: scale(1.03); }',
           'Vergiss transition: transform 0.3s; nicht!'],
    'es': ['.profil-karti { width: 280px; padding: 24px; border-radius: 16px; }',
           'display: flex; flex-direction: column; align-items: center;',
           '.profil-karti:hover { transform: scale(1.03); }',
           '¡No olvides transition: transform 0.3s;!'],
   },
  },

 },

 'lib/courses/data/arduino_lessons_data.dart': {

  'a5_1_project': {
   'requirements': {
    'tr': ['"mesafe" değişkeni oluştur ve ultrasonik sensörden gelen değeri (yuvarlanmış) içine yaz',
           '"sürekli tekrarla" içinde mesafeyi sürekli güncelle',
           "Mesafe 20 cm'den küçükse buzzer'dan alarm sesi çal",
           'Mesafe uzaksa buzzer sessiz kalsın'],
    'en': ['Create a "mesafe" (distance) variable and store the rounded ultrasonic reading in it',
           'Keep the distance up to date inside "forever"',
           'If the distance is under 20 cm, sound the alarm on the buzzer',
           'If it is far away, the buzzer stays silent'],
    'de': ['Lege eine Variable "mesafe" (Abstand) an und speichere darin den gerundeten Ultraschallwert',
           'Halte den Abstand in "wiederhole fortlaufend" aktuell',
           'Ist der Abstand kleiner als 20 cm, lass den Summer Alarm geben',
           'Ist er weit weg, bleibt der Summer still'],
    'es': ['Crea una variable "mesafe" (distancia) y guarda en ella la lectura ultrasónica redondeada',
           'Mantén la distancia actualizada dentro de "por siempre"',
           'Si la distancia es menor de 20 cm, haz sonar la alarma en el zumbador',
           'Si está lejos, el zumbador se queda en silencio'],
   },
   'hints': {
    'tr': ['mesafe değişkenini, "mesafe algılayıcı 12 trig pin 13 echo pin" bloğunun yuvarlanmış hâli yap',
           'eğer <mesafe < 20> ise → "pinde çal ... nota ... ile ... vuruş"',
           'Devre şemasını Robolink ve Kodluyoruz Derneği kitapçıklarından referans al'],
    'en': ['Set mesafe to the rounded value of "read ultrasonic sensor trig pin 12 echo pin 13"',
           'if <mesafe < 20> then → "play pin ... with note ... for ... beats"',
           'Use the circuit diagrams in the Robolink and Kodluyoruz Derneği booklets as a reference'],
    'de': ['Setze mesafe auf den gerundeten Wert von "read ultrasonic sensor trig pin 12 echo pin 13"',
           'falls <mesafe < 20>, dann → den Notenblock des Pins spielen lassen',
           'Nimm die Schaltpläne aus den Heften von Robolink und Kodluyoruz Derneği als Vorlage'],
    'es': ['Da a mesafe el valor redondeado de "lee sensor de ultrasonidos, pin de activación 12, pin de eco 13"',
           'si <mesafe < 20> entonces → "toca nota ... en pin ... durante ... tiempos"',
           'Usa los esquemas de los cuadernillos de Robolink y Kodluyoruz Derneği como referencia'],
   },
  },

  'a5_2_project': {
   'requirements': {
    'tr': ['"yağmur" değişkeni oluştur ve A0 analog pininden oku',
           'Önce kuru/ıslak değerlerini gözlemleyip doğru eşik değerini bul',
           '"eğer <yağmur eşik değerinden küçük/büyük> ise" ile ıslaklığı kontrol et',
           'Islaklık algılanınca servo motoru 0 ile 90 derece arasında hareket ettir (silecek benzetimi)',
           'Kuruyken servo hareket etmesin'],
    'en': ['Create a "yağmur" (rain) variable and read it from analog pin A0',
           'First watch the dry and wet values and find the right threshold yourself',
           'Check for wetness with "if <yağmur is below/above the threshold> then"',
           'When wetness is detected, sweep the servo between 0 and 90 degrees (a wiper simulation)',
           'While it is dry the servo does not move'],
    'de': ['Lege eine Variable "yağmur" (Regen) an und lies sie vom Analogpin A0',
           'Beobachte zuerst die trockenen und nassen Werte und finde deinen Schwellenwert',
           'Prüfe die Nässe mit "falls <yağmur unter/über dem Schwellenwert>, dann"',
           'Bewege den Servo bei Nässe zwischen 0 und 90 Grad (Scheibenwischer-Simulation)',
           'Solange es trocken ist, bewegt sich der Servo nicht'],
    'es': ['Crea una variable "yağmur" (lluvia) y léela del pin analógico A0',
           'Primero observa los valores en seco y en mojado y halla tu propio umbral',
           'Comprueba la humedad con "si <yağmur por debajo/encima del umbral> entonces"',
           'Al detectar humedad, mueve el servo entre 0 y 90 grados (simulación de limpiaparabrisas)',
           'Mientras esté seco el servo no se mueve'],
   },
   'hints': {
    'tr': ['yağmur değişkenini "analog oku pin (A) 0" yap',
           'Önce "seri porta <yağmur> yaz" ile değerleri gözlemle',
           'Servo bloklarını "eğer ... ise" bloğunun içine yerleştir'],
    'en': ['Set yağmur with "read analog pin (A) 0"',
           'Watch the values first with "write <yağmur> to serial port"',
           'Put the servo blocks inside the "if ... then" block'],
    'de': ['Setze yağmur mit "analogen Pin（A）0 lesen"',
           'Beobachte die Werte zuerst mit "<yağmur> an serielle Schnittstelle schreiben"',
           'Lege die Servo-Blöcke in den Block "falls ..., dann"'],
    'es': ['Da valor a yağmur con "lee pin analógico 0"',
           'Observa primero los valores con "escribe <yağmur> al puerto serie"',
           'Coloca los bloques del servo dentro del bloque "si ... entonces"'],
   },
  },

 },
}
